# Generated by Django 4.1.5 on 2023-01-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('open', 'open'), ('completed', 'completed')], max_length=15),
        ),
    ]
